---
# control
control:
  data_name: MNIST
  model_name: mlp-128-1-2-relu
  prune_iters: 30
  prune_mode: si-layer-1-0.5-0
# experiment
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
verbose: False
