---
# control
control:
  teacher_data_name: MNIST
  teacher_model_name: conv
  num_teachers: 1
  data_split_mode: iid
  student_data_name: MNIST
  student_model_name: conv
# experiment
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
verbose: False
